### ISSUE TITLE
Expand environment variables in S3 run step name

### ISSUE THREAD

**Issue by joshunger** [CircleCI-Public/circleci-orbs#65] opened 2018-11-19 14:50 UTC
Would it be possible to expand the environment variables in the S3 run step name?

**Actual behavior:**
![image](https://user-images.githubusercontent.com/2301847/48714248-7fd19780-ebcf-11e8-88e7-36286b91f78a.png)

**Hoping for:** 
![image](https://user-images.githubusercontent.com/2301847/48714321-b4ddea00-ebcf-11e8-8975-0f28d45ef2e6.png)

**Comment by iynere** [comment] 2018-11-27 18:50
@joshunger does the correct value appear in the step output itself ?

if the issue is just about the step name, then this is a higher-level issue that unfortunately can't be resolved here. however, that step name could use a rework either way, & i think we could come up with something better that doesn't depend on an env var at all...

**Comment by joshunger** [comment] 2018-11-28 12:47
@iynere does this help?
![image](https://user-images.githubusercontent.com/2301847/49152764-12a9ba80-f2d1-11e8-92af-e4230fb570fa.png)

**Comment by iynere** [comment] 2018-11-28 16:19
ok, then this is an issue of: 

> this is a higher-level issue that unfortunately can't be resolved here. however, that step name could use a rework either way, & i think we could come up with something better that doesn't depend on an env var at all...

PRs welcome to address ^^ otherwise i will get to it shortly

ty ! @joshunger

**Comment by joshunger** [comment] 2018-11-28 18:20
Can you restate what you are specifically looking for in a PR? Thanks.

**Comment by iynere** [comment] 2018-11-28 19:46
a reworked step name that does not try to include the value of an environment variable (which will never be successfully interpolated in the desired manner) @joshunger

**Comment by KyleTryon** [comment] 2020-01-30 19:47
Issue has been answered. Closing. Thank you.

**Closed by KyleTryon** 2020-01-30 19:47 UTC
